# Generated by Django 5.0.2 on 2024-02-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='date')),
                ('full_url', models.URLField(max_length=250)),
                ('image_url', models.URLField(max_length=250)),
                ('description', models.TextField()),
                ('categories', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'post',
                'ordering': ['-date'],
            },
        ),
    ]
