# Generated by Django 5.0.2 on 2024-02-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VNDisplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date']},
        ),
    ]
