# Generated by Django 5.0.2 on 2024-02-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNDisplay', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='VNDisplay.category'),
        ),
    ]
