# Generated by Django 5.0.2 on 2024-02-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNDisplay', '0005_remove_post_categories_post_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Android_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('full_url', models.URLField(max_length=250)),
                ('image_url', models.URLField(max_length=250)),
            ],
            options={
                'db_table': 'android_post',
            },
        ),
    ]
