# Generated by Django 5.0.2 on 2024-02-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNDisplay', '0008_type_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synopsis', models.TextField()),
                ('image_urls', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VNDisplay.post')),
            ],
        ),
    ]
