# Generated by Django 5.0.2 on 2024-02-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VNDisplay', '0009_postdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdetail',
            old_name='details',
            new_name='features',
        ),
    ]
