# Generated by Django 5.0.2 on 2024-02-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VNDisplay', '0010_rename_details_postdetail_features'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postdetail',
            table='post_detail',
        ),
    ]
