# Generated by Django 5.0.2 on 2025-01-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNDisplay', '0013_rename_publicaction_date_post_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_url',
            field=models.URLField(max_length=300),
        ),
    ]
