# Generated by Django 5.0.2 on 2025-01-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNDisplay', '0014_alter_post_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='android_post',
            name='image_url',
            field=models.URLField(max_length=300),
        ),
    ]
